job:
  before_script:
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
  script:
    - git fetch
    - var=$(git describe --tags)
    - version=${var:1}
    - git push "https://${GITLAB_USER_NAME}:3ozBDRjysM2dXsDMN4tX@${CI_REPOSITORY_URL#*@}" --delete f-droid
    - git checkout -b f-droid
    - sed -i "s#versionCode appVersionCode#versionCode $version#" app/build.gradle
    - sed -i "s#versionName appVersionName#versionName $version#" app/build.gradle
    - git add app/build.gradle
    - git commit -m "update to $version"
    - git push "https://${GITLAB_USER_NAME}:3ozBDRjysM2dXsDMN4tX@${CI_REPOSITORY_URL#*@}"
    - cat app/build.gradle
  only:
    - tags
